{
  "data": {
    "mergePullRequest": null
  },
  "errors": [
    {
      "type": "NOT_FOUND",
      "path": [
        "mergePullRequest"
      ],
      "locations": [
        {
          "line": 6,
          "column": 3
        }
      ],
      "message": "Could not resolve to a node with the global id of 'invalid'"
    }
  ]
}
